spring:
  application:
    name: Brief15
  datasource:
    url: jdbc:h2:mem:bibliotheque
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
  h2:
    console:
      enabled: true
server:
  port: 8080
  servlet:
    context-path: /api