CREATE TABLE emprunt
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_emprunt  date,
    date_retour   date,
    emprunteur_id BIGINT                                  NOT NULL,
    livre_id      BIGINT                                  NOT NULL,
    CONSTRAINT pk_emprunt PRIMARY KEY (id)
);

CREATE TABLE emprunteur
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nom    VARCHAR(255),
    prenom VARCHAR(255),
    email  VARCHAR(255),
    CONSTRAINT pk_emprunteur PRIMARY KEY (id)
);

CREATE TABLE genre
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nom VARCHAR(255),
    CONSTRAINT pk_genre PRIMARY KEY (id)
);

CREATE TABLE livre
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    author      VARCHAR(255),
    CONSTRAINT pk_livre PRIMARY KEY (id)
);

CREATE TABLE livre_genre
(
    genre_id BIGINT NOT NULL,
    livre_id BIGINT NOT NULL,
    CONSTRAINT pk_livre_genre PRIMARY KEY (genre_id, livre_id)
);

ALTER TABLE emprunteur
    ADD CONSTRAINT uc_emprunteur_email UNIQUE (email);

ALTER TABLE emprunt
    ADD CONSTRAINT FK_EMPRUNT_ON_EMPRUNTEUR FOREIGN KEY (emprunteur_id) REFERENCES emprunteur (id);

ALTER TABLE emprunt
    ADD CONSTRAINT FK_EMPRUNT_ON_LIVRE FOREIGN KEY (livre_id) REFERENCES livre (id);

ALTER TABLE livre_genre
    ADD CONSTRAINT fk_livgen_on_genre FOREIGN KEY (genre_id) REFERENCES genre (id);

ALTER TABLE livre_genre
    ADD CONSTRAINT fk_livgen_on_livre FOREIGN KEY (livre_id) REFERENCES livre (id);