INSERT INTO genre (nom) VALUES
                            ('Science Fiction'),
                            ('Policier'),
                            ('Horreur'),
                            ('Romance'),
                            ('Aventure'),
                            ('Biographie'),
                            ('Comédie'),
                            ('Thriller');

INSERT INTO livre (title, author) VALUES
                                    ('Le Trône de Fer', 'George R.R. Martin'),
                                    ('Dune', 'Frank Herbert'),
                                    ('1984', 'George Orwell'),
                                    ('Harry Potter à l''école des sorciers', 'J.K. Rowling'),
                                    ('Le Seigneur des Anneaux', 'J.R.R. Tolkien'),
                                    ('La Couleur des sentiments', 'Kathryn Stockett'),
                                    ('Shining', 'Stephen King'),
                                    ('Ca', 'Stephen King'),
                                    ('Le Parfum', 'Patrick Süskind'),
                                    ('Le Silence des Agneaux', 'Thomas Harris'),
                                    ('Pulp Fiction', 'Quentin Tarantino'),
                                    ('Reservoir Dogs', 'Quentin Tarantino'),
                                    ('Kill Bill', 'Quentin Tarantino'),
                                    ('Les Misérables', 'Victor Hugo'),
                                    ('La Divine Comédie', 'Dante Alighieri'),
                                    ('Cyrano de Bergerac', 'Edmond Rostand'),
                                    ('L''étranger', 'Albert Camus'),
                                    ('Crime et Châtiment', 'Fiodor Dostoïevski'),
                                    ('La Peste', 'Albert Camus'),
                                    ('Dracula', 'Bram Stoker');

INSERT INTO livre_genre (livre_id, genre_id) VALUES
                                                 (1, 5),
                                                 (1, 4),
                                                 (2, 1),
                                                 (2, 5),
                                                 (3, 8),
                                                 (4, 5),
                                                 (4, 4),
                                                 (5, 5),
                                                 (6, 4),
                                                 (7, 3),
                                                 (7, 8),
                                                 (8, 3),
                                                 (9, 8),
                                                 (9, 4),
                                                 (10, 8),
                                                 (11, 2),
                                                 (12, 2),
                                                 (13, 5),
                                                 (14, 4),
                                                 (15, 4),
                                                 (15, 5),
                                                 (16, 5),
                                                 (16, 6),
                                                 (17, 8),
                                                 (18, 8),
                                                 (19, 8),
                                                 (20, 3);

INSERT INTO emprunteur (nom, prenom, email) VALUES
                                                ('Vincent', 'Vega', 'vincent.vega@example.com'),
                                                ('Jules', 'Winnfield', 'jules.winnfield@example.com'),
                                                ('Mia', 'Wallace', 'mia.wallace@example.com'),
                                                ('Butch', 'Coolidge', 'butch.coolidge@example.com'),
                                                ('Marsellus', 'Wallace', 'marsellus.wallace@example.com'),
                                                ('Mr.', 'White', 'mr.white@example.com'),
                                                ('Mr.', 'Orange', 'mr.orange@example.com'),
                                                ('Mr.', 'Blonde', 'mr.blonde@example.com'),
                                                ('The', 'Bride', 'the.bride@example.com'),
                                                ('O-Ren', 'Ishii', 'o.ren.ishii@example.com');

INSERT INTO emprunt (date_emprunt, date_retour, emprunteur_id, livre_id) VALUES
                                                                             ('2025-01-01', NULL, 1, 1),
                                                                             ('2025-01-02', NULL, 2, 2),
                                                                             ('2025-01-03', NULL, 3, 3),
                                                                             ('2025-01-04', NULL, 4, 4),
                                                                             ('2025-01-05', NULL, 5, 5),
                                                                             ('2025-01-06', NULL, 6, 6),
                                                                             ('2025-01-07', NULL, 7, 7),
                                                                             ('2025-01-08', NULL, 8, 8),
                                                                             ('2024-12-20', '2024-12-27', 9, 9),
                                                                             ('2024-12-15', '2024-12-25', 10, 10);
